# Copyright (c) 2023 Hitachi Vantara, Inc. All rights reserved.
# Author: Claude Assistant
#
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# v1.0
#
- name: demo - hostgroup_wwn_create
  hosts: localhost
  gather_facts: false
  become: true
  collections:
    - hitachivantara.mfstorage_raidcom

  tasks:
    - name: Add WWN to host group
      hostgroup_wwn:
        #connectivity
        horcm_inst: "{{ horcm_inst }}"
        storage_serial: "{{ storage_serial }}"
        #properties
        state: present
        port_id: "{{ port_id }}"
        host_grp_number: "{{ host_grp_number }}"
        hba_wwn: "{{ hba_wwn }}"
        wwn_nickname: "{{ wwn_nickname }}"
      register: results

    - name: Display the created host group WWN
      debug:
        msg: "{{results}}"
