# Copyright (c) Hitachi Vantara Corporation 2025. All rights reserved
# Author: Krishi Jain <krishi.jain@hitachivantara.com>
#
# Description:
# Add WWN to the host group
#
# Usage:
# ansible-playbook hostgroup_wwn_create.yml
#
- name: demo - hostgroup_wwn_create
  hosts: localhost
  gather_facts: false
  become: true
  collections:
    - hitachivantara.mfstorage_raidcom

  tasks:
    - name: Add WWN to host group
      hostgroup_wwn:
        #connectivity
        horcm_inst: "{{ horcm_inst }}"
        storage_serial: "{{ storage_serial }}"
        #properties
        state: present
        port_id: "{{ port_id }}"
        host_grp_number: "{{ host_grp_number }}"
        hba_wwn: "{{ hba_wwn }}"
        wwn_nickname: "{{ wwn_nickname }}"
      register: results

    - name: Display the created host group WWN
      debug:
        msg: "{{results}}"
