# Copyright (c) 2023 Hitachi Vantara, Inc. All rights reserved.
# Author: Claude Assistant
#
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# v1.0
#
- name: demo - snapshot_create
  hosts: localhost
  gather_facts: false
  become: true
  collections:
    - hitachivantara.mfstorage_raidcom

  tasks:
    - name: Create snapshot
      snapshot:
        #connectivity
        horcm_inst: "{{ horcm_inst }}"
        storage_serial: "{{ storage_serial }}"
        #properties
        state: present
        pvol: "{{ pvol }}"
        svol: "{{ svol }}"
        pool_id: "{{ pool_id }}"
        snapshot_group_name: "{{ snapshot_group_name }}"
        # Optional
        # mu_numbers: "{{ mu_numbers }}"
        # snap_mode: "cascade"
      register: results

    - name: Display the created snapshot
      debug:
        msg: "{{results}}"
