# Copyright (c) 2021 Hitachi Vantara, Inc. All rights reserved.
# Author: Krishi Jain <krishi.jain@hitachivantara.com>
#
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# v1.0
#
- name: demo - mfvvol_create
  hosts: localhost
  gather_facts: false
  become: true
  collections:
    - hitachivantara.mfstorage_raidcom

  tasks:
    - name: Create MF VVOLs
      vvol:
        #connectivity
        horcm_inst: 1
        storage_serial: 530642
        #properties
        state: present
        pool_name: "2"
        num_ldevs: 1
        ldev_prefix: "00:10:"
        initial_hex: "11"
        base_ldev_name: "VK_Test_LDEV_"
        name_start: 17
        cylinder: 10
        emulation: "3390-A"
      register: results

    - name: Display the created MF VVOLs
      debug:
        msg: "{{results}}"
